### ISSUE TITLE
Wrong call for GET_MANY

### ISSUE THREAD

**Issue by gmcadosch** [tomberek/aor-postgrest-client#16]
PostgREST expects braces around the list of ids even if it's only one (eg. "id=in.(1)"). Currently "convertRESTRequestToHTTP" creates a request without the braces. Hence, PostgREST returns an error.

Here's the fix:
case _reactAdmin.GET_MANY:
                {
                    url = apiUrl + '/' + resource + '?id=in.(' + params.ids.join(',') + ')';
                    break;
                }

**Comment by tomberek** [comment]
Fixed by #11?
