### ISSUE TITLE
Add data property to all responses

### ISSUE THREAD

**Issue by fzaninotto** [tomberek/aor-postgrest-client#2]
The future release of admin-on-rest changes the expected format for REST responses (see https://github.com/marmelab/admin-on-rest/pull/385). It should be released within 2 weeks. 

You need to release a new major version of aor-postgrest-client to take this change into account.

**Comment by nextstopsun** [comment]
@fzaninotto Is `REST response must contain a data key` message connected to this issue? I'm trying to use this fork https://github.com/cleany/aor-postgrest-client/tree/publish 
But with no luck.

It has `data` key in response [here](https://github.com/cleany/aor-postgrest-client/blob/publish/src/index.js#L138). 

Sorry for writing here, the fork doesn't have issues enabled and I'm very new to AOR - can't figure out what is wrong. Can you please help me out?

**Comment by fzaninotto** [comment]
I don't maintain this package. You should ask the author.

**Comment by JCFerrerG** [comment]
PR https://github.com/tomberek/aor-postgrest-client/pull/3 attempts to fix this issue.

In manual testing with AOR 1.3.2, fetching works to some extent, although it is unclear how well or completely it works. 

When CREATEing an entity, the user gets this error:
```
bundle.js:266613 REST response must contain a data key
__stack_frame_overlay_proxy_console__ @ bundle.js:266613
handleResponse$ @ bundle.js:18028
tryCatch @ bundle.js:292109
invoke @ bundle.js:292343
prototype.(anonymous function) @ bundle.js:292161
next @ bundle.js:290125
proc @ bundle.js:290084
runForkEffect @ bundle.js:290367
runEffect @ bundle.js:290248
next @ bundle.js:290129
currCb @ bundle.js:290201
takeCb @ bundle.js:290279
put @ bundle.js:289273
(anonymous) @ bundle.js:289361
(anonymous) @ bundle.js:289382
emit @ bundle.js:289226
(anonymous) @ bundle.js:289786
dispatch @ bundle.js:291388
(anonymous) @ bundle.js:291278
(anonymous) @ bundle.js:290302
exec @ bundle.js:290941
flush @ bundle.js:290982
asap @ bundle.js:290955
runPutEffect @ bundle.js:290299
runEffect @ bundle.js:290248
next @ bundle.js:290129
currCb @ bundle.js:290201
Promise resolved (async)
resolvePromise @ bundle.js:290263
runCallEffect @ bundle.js:290330
runEffect @ bundle.js:290248
next @ bundle.js:290129
currCb @ bundle.js:290201
checkEffectEnd @ bundle.js:290425
chCbAtKey @ bundle.js:290440
currCb @ bundle.js:290201
(anonymous) @ bundle.js:290312
exec @ bundle.js:290941
flush @ bundle.js:290982
asap @ bundle.js:290955
(anonymous) @ bundle.js:289385
emit @ bundle.js:289226
(anonymous) @ bundle.js:289786
(anonymous) @ bundle.js:291417
Create._this.save @ bundle.js:4744
(anonymous) @ bundle.js:7906
doSubmit @ bundle.js:287552
handleSubmit @ bundle.js:287614
(anonymous) @ bundle.js:286411
(anonymous) @ bundle.js:287277
SaveButton._this.handleClick @ bundle.js:4187
EnhancedButton._this.handleTouchTap @ bundle.js:234977
callCallback @ bundle.js:247517
invokeGuardedCallbackDev @ bundle.js:247556
invokeGuardedCallback @ bundle.js:247413
invokeGuardedCallbackAndCatchFirstError @ bundle.js:247427
executeDispatch @ bundle.js:247650
executeDispatchesInOrder @ bundle.js:247672
executeDispatchesAndRelease @ bundle.js:248187
executeDispatchesAndReleaseTopLevel @ bundle.js:248198
forEachAccumulated @ bundle.js:248164
processEventQueue @ bundle.js:248357
runEventQueueInBatch @ bundle.js:248369
handleTopLevel @ bundle.js:248379
handleTopLevelImpl @ bundle.js:248018
batchedUpdates @ bundle.js:259456
performFiberBatchedUpdates @ bundle.js:247864
stackBatchedUpdates @ bundle.js:247855
batchedUpdates @ bundle.js:247869
batchedUpdatesWithControlledComponents @ bundle.js:247882
dispatchEvent @ bundle.js:248092
bundle.js:266613 Warning: Missing translation for key: "REST response must contain a data key"
```

AOR version: 1.3.2
React: 16
Browser: Chromium 60

**Comment by jferrer-vhm** [comment]
This is a good start for a nice contribution back to tomberek/aor-postgrest-client.  I do not know if the airbnb config complies with the [admin-on-rest code style guidelines](https://github.com/marmelab/admin-on-rest/blob/master/.github/CONTRIBUTING.md#coding-style), but if you haven't already, consider keeping this module's guidelines consistent with the parent project.

**Comment by tomberek** [comment]
PR #3 is closed. Is there still a problem?

**Comment by tomberek** [comment]
Please reopen if the current version (0.2.5) still doesn't work for you.
