### ISSUE TITLE
Resolves too many React dependencies when used with admin-on-rest 1.3.2

### ISSUE THREAD

**Issue by JCFerrerG** [tomberek/aor-postgrest-client#6]
When using admin-on-rest 1.3.2 with this package, it causes admin-on-rest@^0.7.0 to be loaded with an older, conflicting version of React.  This prevents the app from starting.

This does not apply to current trunk, which does not support the new REST response format, but it will once #2 is fixed -- possibly by accepting PR https://github.com/tomberek/aor-postgrest-client/pull/3.

**Comment by tomberek** [comment]
#2 and #3 closed. Please reopen if this is still an issue.
