### ISSUE TITLE
Copy repo into tomberek/ra-postgrest-client

### ISSUE THREAD

**Issue by christiaanwesterbeek** [tomberek/aor-postgrest-client#8]
A few weeks back I upgraded from [admin-on-rest](https://github.com/marmelab/admin-on-rest) to [react-admin](https://github.com/marmelab/react-admin). I had to change a few things to this postgrest client in order for it to be compatible with react-admin.

Care to [copy](https://stackoverflow.com/questions/22767617/copy-fork-a-git-repo-on-github-into-same-organization) this repo into `tomberek/ra-postgrest-client`?

Afterwards, I will propose some PR's to it with the changes I had to make.

**Comment by alfonsodev** [comment]
@tsingson published `ra-posgrest-client` on npm https://github.com/tsingson/ra-postgrest-client

**Comment by afmichelutti** [comment]
@tomberek @tsingson
Hello! can you tell me if there is already the version of ra-postgrest-client compatible with react-admin?
Tks!
